### ISSUE TITLE
채팅 기능 개발 정의서

### ISSUE THREAD

**Issue by gutanbug** [EveryUniv/next-student-council-backend#44]
WithDankook 서비스에서 단터디, Bear 이츠, 구해줘 룸메, 단혼밥, 단국거래 모두에서 사용할 채팅 기능을 추가해야한다.
채팅 기능은 모듈성을 위해 연관관계가 최대한 없게 설계해야한다. 추가해야할 기능으로는
- 채팅방 생성
- 채팅방 조회
- 서비스별 채팅방 조회
- 채팅 조회
- 채팅 발신/수신

채팅 기능을 개발함에 있어 Redis를 사용한 캐시처리 , DynamoDB, pub/sub를 이용한 채팅 기능 등 여러가지 기술을 필요로 하기 때문에 사전에 관련된 지식을 필요로 한다. 앞서 말한 기술을 다 사용할 필요는 없지만 사용하면 효율적인 부분은 챙길 수 있다.

**채팅방 생성**
이 기능은 WithDankook 서비스 게시글에서 사용자가 신청하는 순간에 생성되어 DB에 저장되야한다.
이때, 단국거래/구해줘룸메 는 개별적으로 채팅 서비스가 필요하기 때문에 신청한 사용자와 게시글 작성자 둘만 있는 방으로만 생성되고 나머지 3개의 서비스에서는 단체로 접속 가능한 채팅방이여야 한다.

**채팅방 조회/서비스별 채팅방 조회**
채팅방 조회 시 자신이 올린 게시글 별로 단일 개의 채팅방 또는 여러 개의 채팅방이 있을 수 있다. 먼저, 서비스 별로 채팅방을 구분하고 게시글 이름을 전달해주어 어떤 게시글에서 만들어진 채팅방인지 구분되어야 한다. 또한, 채팅방 순서는 가장 최근에 보내거나 온 채팅 메시지 시간에 따라서 최신순으로 정렬되어야 한다.

**채팅 발신/수신**
Spring Boot에서 pub/sub 기능을 이용하여 기능을 개발하거나, Node.js 로 구현할 수 있다. 과부하 테스트를 진행하여 성능적으로 문제가 없는지 확인하고 추후 다른 서비스에서도 쉽게 사용할 수 있도록 모듈화하는 것이 중요하다. 

추후에 채팅 기능 고도화는 메시지 뿐만이 아닌 이미지, 동영상도 추가하거나 알림 기능, 안 읽은 메시지 개수 처리 등 최대한 지금 존재하는 채팅 서비스와 거의 동일하게 개발하는 것이 좋을 것 같다.

**Comment by won983212** [comment]
안녕하세요~ 지나가다가 살짝 코멘트 남겨봅니다 ㅎㅎ

Spring Boot의 pub/sub는 Client와 Server간 통신이 아닌 **Server끼리의 통신**, 즉 서버 컴포넌트간 통신에 사용되는 기술인데요. 그래서 채팅을 구현하려면 결국 Client, Server간 통신을 위해서 WebSocket등의 기술을 추가로 사용해야할 것 같습니다.

그러면 말씀하신대로 WebSocket으로 클라이언트와 통신하기 위해서, 어떤 기술을 사용할 것인지 (Spring / Node.js중 하나)를 선택하셔야 해요.
Node.js가 event기반으로 비동기 처리(하나의 thread가 다수의 connection컨트롤)에 특화되어있어서 성능적으로는 좀 더 괜찮을 것 같아요. 대신...
- Node.js를 따로 배워야합니다.
  - 새로 배워야하는 만큼, Spring으로 개발했을 때보다 더 꼼꼼하게 보시기는 어려울 것 같아요.
  - 그래서 추가로 개발/검증 비용도 늘어납니다.
- 소규모의 채팅 시스템이라면 성능 차이가 크진 않을거에요. (성능테스트 필요)

이건 각 기술의 trade-off를 잘 고민해보시고 선택하면 될 것 같아요!
