### ISSUE TITLE
[With-Dankook] 채팅 기능 기술 선택 관련

### ISSUE THREAD

**Issue by kjungw1025** [EveryUniv/next-student-council-backend#54]
# SpringBoot + WebSocket / STOMP
Stomp로 채팅을 구현시 사용자가 채팅방에 접속했을때 해당 채팅방을 구독하기만 한다면 
누가 접속중인지 따로 관리하지 않아도 메시지를 보낸 사용자가 포함된 채팅방의 모든 사람에게 메시지가 갈 수 있다는 강점을 가지고 있다. WebSocket에 추가로 STOMP 프로토콜을 사용한다면, WebSocket만 이용할 때 보다 더 풍부한 프로그래밍 모델을 제공할 수 있다.

# SockJS
SockJS는 애플리케이션이 우선적으로 WebSocket API를 사용하도록 하지만, 사용할 수 없는 경우에는 런타임 시점에 코드 변경 없이 WebSocket 이외의 대안 (HTTP, Long Polling 등)으로 대체한다.
자세한 내용은 아래 링크 참고 
https://github.com/sockjs/sockjs-client#supported-transports-by-browser-html-served-from-http-or-https

#### 서버 쪽 설정
스프링은 WebSocket 또는 SockJS 기반으로 STOMP를 위해 관련 모듈을 제공하고 있고,
기본적으로 커넥션을 위한 STOMP Endpoint를 설정해야만 한다.
<img src="https://github.com/EveryUniv/next-student-council-backend/assets/120318020/e0535f5f-bc2d-4345-be95-618866264f26" width="600" height="300"/>

#### 클라이언트 쪽 설정
<b>추후 프론트엔드 쪽에서 개발 진행시 SockJS 기술을 적용해줘야 한다.</b>
브라우저인 클라이언트 측면에서는 SockJS 프로토콜을 사용하기 위해서 sockjs-client 라이브러리를 사용한다. 
또한, 최근에 STOMP 프로토콜의 클라이언트 라이브러리는 webstomp-client을 많이 사용한다고 하니 참고 바람
<img src="https://github.com/EveryUniv/next-student-council-backend/assets/120318020/a78d2c88-ccc0-40c2-bb76-aacf83c92548" width="600" height="500"/>

# External Broker (Kafka vs RabbitMQ vs Redis)
Spring WebSocket에서 STOMP 프로토콜을 사용하여 채팅 기능을 구현할 때, STOMP는 Message Broker가 필요하다.
이때 아무 설정 없이 Spring 환경에서 STOMP 프로토콜을 사용한다면, 메시지 브로커로 <b>In Memory Broker</b>를 사용하게 된다.
In Memory Broker 사용 시 문제점
1. 세션을 수용할 수 있는 크기 제한
2. 장애 발생 시 메시지의 유실될 가능성이 높음
3. 따로 모니터링 하는 것이 불편하다.

그러므로 RabbitMQ, Redis와 같은 외부 전용 메시지 브로커를 사용하거나, 메시지 브로커로서도 사용이 가능한 이벤트 브로커인 Kafka를 사용하는 것이 여러가지 측면에서 좋다고 판단하였다.
여기서 메시지 브로커와 이벤트 브로커의 큰 차이점은, 메시지 브로커의 경우 데이터를 보내고, 처리하고 삭제한다. 그러나 이벤트 브로커는 삭제하지 않는다. 이로써 이벤트 스트림에 로그를 계속 유지하기 때문에 에러나 기타 문제가 생겼을 때 이벤트를 재생할 수 있는 큰 장점을 가지고 있다. 또한 메시지의 순서를 보장한다는 점이 채팅방에서 대화한 내역을 순차적으로 NoSQL DB에 저장하기에 매우 용이하다.
위와 같은 이유를 토대로 <b>Kafka</b>를 선택하게 되었다.   

# NoSQL DB (AWS DynamoDB vs MongoDB)
우선 NoSQL이 기존의 RDB보다 더 빠른 읽기 쓰기 성능을 가지고 있기 때문에,
각 채팅방 별, 채팅 내용을 저장하고 불러오기에는 NoSQL을 추가적으로 사용하는게 성능상 더 효과적이라고 판단하였다.
대표적인 NoSQL로 AWS DynamoDB와 MongoDB가 존재하는데 각자의 장단점이 존재하고
현재 <b>DynamoDB</b>를 사용할 것으로 보이며, 추가적인 자료 수집 후 구체적인 구현을 진행해봐야 할 것 같다.

**Comment by kjungw1025** [comment]
현재까지는 로컬 환경에서 Kafka까지 어느정도 적용을 완료한 상태입니다.
추가적으로 발생하는 오류 사항 해결과 성능 테스트를 진행하여 개선시켜 나가보도록 하겠습니다.

<img src="https://github.com/EveryUniv/next-student-council-backend/assets/120318020/4e90d0d7-1bdd-4aa8-8c3c-66f8c14f4577" width="600" height="300"/>

**Comment by developerChans** [comment]
@mintchocojaem  프론트엔드 지원가능한가요?

**Comment by kjungw1025** [comment]
# 전체적인 채팅방 흐름
<img width="1037" alt="스크린샷 2024-05-01 오후 11 09 15" src="https://github.com/EveryUniv/next-student-council-backend/assets/120318020/56601ded-aaf9-4a10-9390-a04e99f0b0c1">
